# Generated by Django 5.2.1 on 2025-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ramanadhapuram_forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('values', models.TextField()),
                ('type', models.CharField(default='Weather radar', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'unique_together': {('city', 'timestamp')},
            },
        ),
    ]
