# Generated by Django 5.2.1 on 2025-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramanadhapuram_forecast',
            name='type',
            field=models.CharField(default='Cloud Coverage', max_length=50),
        ),
    ]
